---
title: "map"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Map  
```{r, maps, warning=FALSE, message=FALSE, include=TRUE}
library(tidyverse)
#library(tmap)
#library(sf)
library(maps)

#relocation data
relocations <- read_csv("../data/Carrizo_telemetry_with_shrub_density.csv")

#map ggplot
states <- map_data("state")
ca_df <- subset(states, region == "california")

map1 <- ggplot(data = ca_df, mapping = aes(x = long, y = lat)) +
  coord_fixed(1.3) +
  geom_polygon(color = "black", fill = "gray") +
  geom_point(relocations, mapping = aes(long, lat, color = mesohabitat)) +
  scale_color_brewer(palette = "Set1") + 
  labs(x = "longitude", y = "latitude", color = "")
map1


map1 + coord_fixed(xlim = c(-118, -122.0),  ylim = c(34, 37), ratio = 1)

#map sf
library(sf)
#library(rnaturalearth)
#library(rnaturalearthdata)
library(USAboundaries)
library(ggspatial)

CA<-us_states(resolution = "high", states = c("California")) %>%
  st_transform(crs = 4326)
world <- ne_countries(scale = "medium", returnclass = "sf")


map2 <- ggplot(data = CA) +
  geom_sf() +
  geom_point(relocations, mapping = aes(long, lat, color = mesohabitat), size = 0.5) +
  scale_color_brewer(palette = "Set1") + 
  labs(x = "longitude", y = "latitude", color = "")
map2

map2 + 
  coord_sf(xlim = c(-118, -122.0),  ylim = c(34, 37)) +
  annotation_scale(location = "bl", width_hint = 0.5)

map3 <- ggplot(data = world) +
  geom_sf() +
  geom_point(relocations, mapping = aes(long, lat, color = mesohabitat), size = 0.5) +
  scale_color_brewer(palette = "Set1") + 
  labs(x = "longitude", y = "latitude", color = "")
map3

map3 + coord_sf(xlim = c(-118, -122.0),  ylim = c(34, 37)) +
  annotation_scale(location = "bl", width_hint = 0.5)

  

```

